### ISSUE TITLE
Please update to newest Opencore and macOS Monterey

### ISSUE THREAD

**Issue by phonex34** [extric99/Hackintosh-Gigabyte-Z390-GAMING-X-i9-9900k-5700XT#12] opened 2021-10-28 09:24 UTC
The macOS Monterey has just been released is this config can work with Monterey? 
Many thanks

**Comment by extric99** [comment] 2021-10-28 11:44
Monterey gives issues with bluetooth after sleep which i have not been able to fix. 
OC 0.7.4 works but I will only publish it when I or Apple is able to fix the bluetooth issue. No idea where the issue is coming from.  For the moment i have no time to work in it.

**Comment by kansonkong** [comment] 2021-10-30 02:26
looking forward to your new release to support Monterey, thank you.

**Comment by phonex34** [comment] 2021-11-02 03:47
> Monterey gives issues with bluetooth after sleep which i have not been able to fix.
> OC 0.7.4 works but I will only publish it when I or Apple is able to fix the bluetooth issue. No idea where the issue is coming from. For the moment i have no time to work in it.


Can you just release only OC 0.7.4 without bluetooth fix, please ? I think there will have many people who don't care about bluetooth issue.

**Comment by extric99** [comment] 2021-11-02 10:52
I am not releasing it as a package but you can download it above.
This is provided "AS IS" meaning I am not supporting or answering questions about it in anyway. 
 I have not fully tested it and and the ACPI section is not final.

**Comment by kansonkong** [comment] 2021-12-08 01:13
Hi, macOS 12.1 RC is released today, will you please check whether the bluetooth issue is fixed? thank you.

**Comment by extric99** [comment] 2021-12-08 07:05
The issue will not be fixed in upcoming MacOS releases because it was a “change by design” that is the source of the problem. Apple redesigned how bluetooth works, the fix needs to come from opencore or kexts.

**Comment by javierlori** [comment] 2021-12-09 11:52
Super out of the loop so I'll be probably wrong. But, weren't the Bluetooth issues fixed with the 2.6.1 BrcmPatchRAM release?

<img width="779" alt="image" src="https://user-images.githubusercontent.com/67294438/145391305-4c4ef12f-251b-4797-89b0-482e6e8bb504.png">

Anyway thank you for your work, looking forward to your next releases! 
Best regards.

**Comment by extric99** [comment] 2021-12-09 12:15
The Fenvi card most people use is a native card and in theory this kext should not impact the card. When i find the time i will try to test but not hopeful.

**Comment by javierlori** [comment] 2021-12-09 12:22
Thank you for your answer! 
I come from your other DNKE build, in which the DW1560 is used, and I use this kext. Didn't realise that you were using a different bluetooth card in this build.

Also, I haven't been able to update the NUC to Monterey, so no idea if this FIX even works in the NUC either.

**Comment by kansonkong** [comment] 2022-01-15 13:38
Sir, OC 0.7.7 have been released, do you have time to verify if the bluetooth issue fixed?  thank you.

this guy post a screen snapshot with bluetooth driven, but he doesn't  address whether the bluetooth works smooth or not.

https://github.com/BenjaminX/Hackintosh-Gigabyte-Z390M-GAMING

**Comment by extric99** [comment] 2022-01-16 16:17
Currently not planning to invest any time to this in short term. I need my machine stable with bluetooth  for other projects and Monterey adds very little for to be honest on Hackintosh for me.

**Comment by kansonkong** [comment] 2022-01-17 02:57
ok, thanks for reply

**Comment by extric99** [comment] 2022-02-03 15:07
I created a BETA version for Opencore 0.7.7 and for me at least it seems to be working correctly.
What I did  
-Update to the latest BIOS version
-Reapply bios settings
-Disabled XMP profile
-Upgraded copy of BigSur on an NVME drive

==> sleep and wake seem to be working fine with the tweaks I did.
==> same for airdrop and handoff

Please test this for yourself and let me know. If it works for multiple people I will release it

update: attachment removed since people don’t bother to provide input

<img width="902" alt="Screenshot 2022-02-03 at 15 51 15" src="https://user-images.githubusercontent.com/33332861/152368581-e8fdfb8d-2c0c-4306-bae9-7d875cdced0d.png">

**Comment by kansonkong** [comment] 2022-02-03 15:38
have you fixed the long boot issue of your samsung 970 EVO ssd? I encountered the same problem as yours by upgrade to monterey from bigsur, when I did a fresh installation, the problem disappeared, now the boot time is less than 10s, you can have a try.

**Comment by extric99** [comment] 2022-02-03 16:35
The samsung drives are not well supported by MacOS and create many issues especially with TRIM as it can destroy the drive.
see https://github.com/dortania/bugtracker/issues/192

I am not using mine anymore and switched to a WD Blue SN550  and it boots in under 10s

**Closed as completed** 2022-02-17 12:28 UTC
